-- Per-milestone (roadmap step) TODO checklist items.
--
-- Each row is one concrete, checkable action item belonging to a roadmap step
-- (a milestone). Items are generated by the LLM for a step and can be ticked off
-- manually or auto-ticked from a check-in note. Ownership is derived through the
-- step -> roadmap -> goal chain (`goals.user_id`); there is no direct user_id
-- column here. `done` is an integer 0/1 flag; `done_at` is the Rfc3339 completion
-- timestamp, NULL unless `done` is 1.
CREATE TABLE step_todos (
    id         TEXT PRIMARY KEY,
    step_id    TEXT NOT NULL,            -- roadmap_steps.id
    ord        INTEGER NOT NULL,
    title      TEXT NOT NULL,
    done       INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,            -- Rfc3339
    done_at    TEXT                      -- Rfc3339, NULL unless done
);
CREATE INDEX idx_step_todos_step ON step_todos(step_id);
