//! The MCP server handler: the tool surface.
//!
//! Tools are declared with rmcp's `#[tool_router]`/`#[tool]`/`#[tool_handler]`
//! macros. Every handler resolves the request's authenticated user (injected by
//! [`super::auth`]) and scopes all queries to that `user_id`, enforcing the same
//! per-user ownership the REST routes do — a tool acting on another user's goal
//! or step is refused, never executed.

use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{CallToolResult, ContentBlock, ServerCapabilities, ServerConfig};
use rmcp::service::RequestContext;
use rmcp::{tool, tool_handler, tool_router, ErrorData as McpError, RoleServer, ServerHandler};
use serde::Deserialize;
use serde_json::json;
use time::format_description::well_known::Rfc3339;
use time::OffsetDateTime;

use super::auth::AuthUser;
use crate::state::AppState;

/// One MCP server instance. A fresh one is built per session by the service
/// factory (see [`super::service`]), each capturing process-wide [`AppState`].
///
/// Note there is deliberately no `tool_router` field: rmcp's `#[tool_handler]`
/// dispatches through the *static* `Self::tool_router()` (generated by
/// `#[tool_router]`), so an instance field would be dead weight.
pub struct McpServer {
    state: AppState,
}

// ---- request-scoped identity ----------------------------------------------

/// Pull the authenticated `user_id` the auth middleware stashed. The rmcp
/// transport forwards the whole `http::request::Parts` into the request
/// context; our [`AuthUser`] lives inside its extensions.
fn require_user(ctx: &RequestContext<RoleServer>) -> Result<String, McpError> {
    let parts = ctx
        .extensions
        .get::<axum::http::request::Parts>()
        .ok_or_else(|| McpError::internal_error("missing request context", None))?;
    let user = parts
        .extensions
        .get::<AuthUser>()
        .ok_or_else(|| McpError::invalid_params("unauthenticated", None))?;
    Ok(user.0.clone())
}

// ---- result helpers -------------------------------------------------------

/// Wrap a serializable value as a single JSON text content block.
fn json_ok<T: serde::Serialize>(value: &T) -> Result<CallToolResult, McpError> {
    let text = serde_json::to_string_pretty(value)
        .map_err(|e| McpError::internal_error(format!("serialize: {e}"), None))?;
    Ok(CallToolResult::success(vec![ContentBlock::text(text)]))
}

/// A client-visible tool error carrying `message` (no internal details).
fn tool_error(message: impl Into<String>) -> CallToolResult {
    CallToolResult::error(vec![ContentBlock::text(message.into())])
}

/// Map a database error to an MCP internal error: the detail is logged, never
/// leaked to the client (mirrors the REST error mapping).
fn db_error(err: sqlx::Error) -> McpError {
    tracing::error!(error = ?err, "mcp tool database error");
    McpError::internal_error("internal error", None)
}

/// Current time as an RFC 3339 string (the format every timestamp column uses).
fn now_rfc3339() -> Result<String, McpError> {
    OffsetDateTime::now_utc()
        .format(&Rfc3339)
        .map_err(|e| McpError::internal_error(format!("time format: {e}"), None))
}

// ---- tool argument types --------------------------------------------------

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct GetGoalArgs {
    /// The goal's id (as returned by `list_goals`).
    goal_id: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct AddProgressNoteArgs {
    /// The goal to annotate (must belong to the caller).
    goal_id: String,
    /// Free-text progress note; replaces the goal's current note.
    note: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct MarkStepDoneArgs {
    /// The roadmap step's id to mark done (its goal must belong to the caller).
    step_id: String,
}

#[tool_router]
impl McpServer {
    pub fn new(state: AppState) -> Self {
        Self { state }
    }

    #[tool(description = "List the authenticated user's goals as \
                       {id, title, status, deadline, category}.")]
    #[allow(clippy::type_complexity)]
    async fn list_goals(
        &self,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let rows: Vec<(String, String, String, Option<String>, Option<String>)> = sqlx::query_as(
            "SELECT id, title, status, deadline, category \
             FROM goals WHERE user_id = ? ORDER BY created_at",
        )
        .bind(&user)
        .fetch_all(&self.state.db)
        .await
        .map_err(db_error)?;

        let goals: Vec<serde_json::Value> = rows
            .into_iter()
            .map(|(id, title, status, deadline, category)| {
                json!({
                    "id": id,
                    "title": title,
                    "status": status,
                    "deadline": deadline,
                    "category": category,
                })
            })
            .collect();
        json_ok(&goals)
    }

    #[tool(
        description = "Get one goal owned by the caller plus its roadmap steps \
                       ({ord, title, detail, due_date, status})."
    )]
    #[allow(clippy::type_complexity)]
    async fn get_goal(
        &self,
        Parameters(args): Parameters<GetGoalArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;

        // Ownership: scope the lookup to the caller — another user's goal simply
        // isn't found, so it can never be read.
        let goal: Option<(
            String,
            String,
            Option<String>,
            Option<String>,
            Option<String>,
            String,
            Option<String>,
            String,
            String,
        )> = sqlx::query_as(
            "SELECT id, title, description, category, deadline, status, progress_note, \
             created_at, updated_at FROM goals WHERE id = ? AND user_id = ?",
        )
        .bind(&args.goal_id)
        .bind(&user)
        .fetch_optional(&self.state.db)
        .await
        .map_err(db_error)?;

        let Some((
            id,
            title,
            description,
            category,
            deadline,
            status,
            progress_note,
            created_at,
            updated_at,
        )) = goal
        else {
            return Ok(tool_error("goal not found"));
        };

        let step_rows: Vec<(i64, String, Option<String>, Option<String>, String)> = sqlx::query_as(
            "SELECT rs.ord, rs.title, rs.detail, rs.due_date, rs.status \
             FROM roadmap_steps rs JOIN roadmaps r ON rs.roadmap_id = r.id \
             WHERE r.goal_id = ? ORDER BY rs.ord",
        )
        .bind(&id)
        .fetch_all(&self.state.db)
        .await
        .map_err(db_error)?;

        let steps: Vec<serde_json::Value> = step_rows
            .into_iter()
            .map(|(ord, title, detail, due_date, status)| {
                json!({
                    "ord": ord,
                    "title": title,
                    "detail": detail,
                    "due_date": due_date,
                    "status": status,
                })
            })
            .collect();

        json_ok(&json!({
            "id": id,
            "title": title,
            "description": description,
            "category": category,
            "deadline": deadline,
            "status": status,
            "progress_note": progress_note,
            "created_at": created_at,
            "updated_at": updated_at,
            "steps": steps,
        }))
    }

    #[tool(
        description = "Set a goal's progress note (replacing any existing note) after \
                       verifying the goal belongs to the caller."
    )]
    async fn add_progress_note(
        &self,
        Parameters(args): Parameters<AddProgressNoteArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let now = now_rfc3339()?;

        // Ownership is enforced in the WHERE clause: the update touches zero rows
        // for a goal the caller doesn't own, so it can never mutate it.
        let result = sqlx::query(
            "UPDATE goals SET progress_note = ?, updated_at = ? WHERE id = ? AND user_id = ?",
        )
        .bind(&args.note)
        .bind(&now)
        .bind(&args.goal_id)
        .bind(&user)
        .execute(&self.state.db)
        .await
        .map_err(db_error)?;

        if result.rows_affected() == 0 {
            return Ok(tool_error("goal not found"));
        }
        json_ok(&json!({ "goal_id": args.goal_id, "updated": true }))
    }

    #[tool(
        description = "Mark a roadmap step done after verifying its roadmap's goal belongs \
                       to the caller."
    )]
    async fn mark_step_done(
        &self,
        Parameters(args): Parameters<MarkStepDoneArgs>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;

        // Ownership: the step is only updated when it belongs to a roadmap whose
        // goal is owned by the caller (subquery), otherwise zero rows change.
        let result = sqlx::query(
            "UPDATE roadmap_steps SET status = 'done' WHERE id = ? AND roadmap_id IN \
             (SELECT r.id FROM roadmaps r JOIN goals g ON r.goal_id = g.id WHERE g.user_id = ?)",
        )
        .bind(&args.step_id)
        .bind(&user)
        .execute(&self.state.db)
        .await
        .map_err(db_error)?;

        if result.rows_affected() == 0 {
            return Ok(tool_error("step not found"));
        }
        json_ok(&json!({ "step_id": args.step_id, "status": "done" }))
    }

    #[tool(description = "Get the caller's wallet balance as {balance_cents, currency}.")]
    async fn get_wallet_balance(
        &self,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResult, McpError> {
        let user = require_user(&ctx)?;
        let wallet: Option<(i64, String)> =
            sqlx::query_as("SELECT balance_cents, currency FROM wallets WHERE user_id = ?")
                .bind(&user)
                .fetch_optional(&self.state.db)
                .await
                .map_err(db_error)?;

        // A user with no wallet row yet has a zero balance in the default currency.
        let (balance_cents, currency) = wallet.unwrap_or((0, "EUR".to_string()));
        json_ok(&json!({ "balance_cents": balance_cents, "currency": currency }))
    }
}

#[tool_handler]
impl ServerHandler for McpServer {
    fn get_info(&self) -> ServerConfig {
        ServerConfig::new(ServerCapabilities::builder().enable_tools().build()).with_instructions(
            "AI Buddy MCP server: an accountability coach. Read the user's goals, drill \
                 into a goal's roadmap steps, record progress notes, mark roadmap steps done, \
                 and check the user's wallet balance. Every tool is scoped to the authenticated \
                 user and refuses to touch another user's data.",
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn now_rfc3339_is_parseable() {
        let ts = now_rfc3339().expect("format now");
        assert!(
            OffsetDateTime::parse(&ts, &Rfc3339).is_ok(),
            "expected RFC 3339, got {ts}"
        );
    }

    #[test]
    fn tool_error_is_an_error_result() {
        let res = tool_error("nope");
        assert_eq!(res.is_error, Some(true));
    }
}
